-- 코드를 입력하세요
SELECT
b.TITLE,
b.BOARD_ID,
r.REPLY_ID,
r.WRITER_ID,
r.CONTENTS,
DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD as b
JOIN USED_GOODS_REPLY as r
ON r.BOARD_ID=b.BOARD_ID
where DATE_FORMAT(b.CREATED_DATE, "%Y-%m-%d") between '2022-10-01' and '2022-10-31'
ORDER BY r.CREATED_DATE, b.TITLE;